.TH "turtel_lex" "1"
.SH "NAME"
turtel_lex
.SH "SYNOPSIS"
turtel_lex [-h] [-e] [-o file] file
.SH "DESCRIPTION"
turtel_lex - turtel lexer
.PP
if file is not specified, turtel_lex will read from stdin
.SH "OPTIONS"
-h 	\- 	show help
.PP
-e 	\- 	create executable /usr/bin/turtel script file (with chmod())
.PP
-o 	\- 	set output
.SH "AUTHOR"
krzysckh (github.com/krzysckh) 2021, 2022
