.TH "turtel" "1"
.SH "NAME"
turtel \- turtel interpreter
.SH "SYNOPSIS"
turtel [-h] [-w] file
.SH "DESCRIPTION"
turtel - turtel lexed code interpreter
.PP
if file is not specified, turtel will read from stdin
.SH "OPTIONS"
.TP
.B -h
show help
.TP
.B -w
show warnings
.SH "SEE ALSO"
.BR turtel_lex(1)
