.TH "turtel" "1"
.SH "NAME"
turtel
.SH "SYNOPSIS"
turtel [-h] [-w] file
.SH "DESCRIPTION"
turtel - turtel lexed code interpreter
.PP
if file is not specified, turtel will read from stdin
.SH "OPTIONS"
-h 	\- 	show help
.PP
-w 	\- 	show warnings
.SH "AUTHOR"
krzysckh (github.com/krzysckh) 2021, 2022
