.TH "turtel_lex" "1"
.SH "NAME"
turtel_lex \- turtel lexer
.SH "SYNOPSIS"
turtel_lex [-h] [-e] [-o file] file
.SH "DESCRIPTION"
turtel_lex - turtel lexer
.PP
if file is not specified, turtel_lex will read from stdin
.SH "OPTIONS"
.TP
.B -h
show help
.TP
.B -e
create executable /usr/bin/turtel script file (with chmod())
.TP
.B -o
set output
.SH "SEE ALSO"
.BR turtel(1)
